# Generated by Django 3.2 on 2022-06-06 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_balance', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=250)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('trx_hash', models.TextField(null=True, verbose_name='Transaction hash')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
