# Generated by Django 3.2 on 2022-06-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=10)),
                ('contract_address', models.TextField(blank=True, null=True)),
                ('abi', models.JSONField(blank=True, null=True)),
                ('is_token', models.BooleanField(default=True)),
            ],
        ),
    ]
