# Generated by Django 4.0 on 2022-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='block_number',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
