# Generated by Django 4.0 on 2022-07-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_erc20_address_transaction_is_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('complete', 'Complete')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
